apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
  namespace: restaurant-services
data:
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
