apiVersion: v1
kind: Secret
metadata:
  name: mongodb-order-secret
  namespace: restaurant-services
type: Opaque
data:
  # Base64 encoded MongoDB Atlas URI for Order service
  MONGOURI: bW9uZ29kYitzcnY6Ly9yZXN0YXVyYW50YWRtaW46QGNsdXN0ZXIwLnNhMm16Lm1vbmdvZGIubmV0L09yZGVyREI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-secret
  namespace: restaurant-services
type: Opaque
data:
  # Base64 encoded MongoDB Atlas URI for Admin service
  MONGOURI: bW9uZ29kYitzcnY6Ly9yZXN0YXVyYW50YWRtaW46QGNsdXN0ZXIwLnNhMm16Lm1vbmdvZGIubmV0L0FkbWluREI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
---
# Add similar secrets for other services
