apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-auth-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: utility-auth-service
  template:
    metadata:
      labels:
        app: utility-auth-service
    spec:
      containers:
        - name: utility-auth-service
          image: ${DOCKER_REGISTRY}/utility-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6969
          env:
            - name: PORT
              value: "6969"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGO_URI_AUTH
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: food-delivery-config
                  key: JWT_SECRET
            - name: TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  name: food-delivery-config
                  key: TOKEN_EXPIRY
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: food-delivery-config
                  key: RABBITMQ_URL
          resources:
            limits:
              cpu: "300m"
              memory: "384Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 6969
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 6969
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: utility-auth-service
  namespace: food-delivery
spec:
  selector:
    app: utility-auth-service
  ports:
    - port: 6969
      targetPort: 6969
  type: ClusterIP
